### ISSUE TITLE
[bug/求助?]  默认配置下，猎人对平民锤击无效，两者对机器碰撞箱失效

### ISSUE THREAD

**Issue by cycode0527** [landmineHQl/ddnet-hidden#1]
如图：
![QQ截图20231216185855](https://github.com/landmineHQ/ddnet-hidden/assets/76815699/f4f7bead-fed7-4342-afe0-f8e6a6ca8df9)
<img width="1280" alt="PixPin_2023-12-16_19-02-51" src="https://github.com/landmineHQ/ddnet-hidden/assets/76815699/16455c49-7eb6-4ed6-8795-8b2aa8a42fc3">
![QQ截图20231216191319](https://github.com/landmineHQ/ddnet-hidden/assets/76815699/97e85a88-c3fd-4a3c-8ace-362724bfeced)

在**默认配置**下，也就是说不修改任何代码和配置文件的情况下，我默认编译后的服务器出现了一下问题：
- 猎人对平民锤击无效。（图三为锤击效果）
- 双方都对机器没有碰撞箱

除此之外正常。

**Comment by LandmineHQ** [comment]
请检查DEVICE是否有无碰撞的buff，同时请检查投票中的kill hammer是否关闭

**Comment by cycode0527** [comment]
> 请检查DEVICE是否有无碰撞的buff，同时请检查投票中的kill hammer是否关闭

在开启游戏前的等待房间，任何人都可以互相击杀，说明killhammer已开启。但在进入游戏后，猎人无法击杀。我并没有在代码层面和配置文件上做任何更改

**Comment by LandmineHQ** [comment]
> > 请检查DEVICE是否有无碰撞的buff，同时请检查投票中的kill hammer是否关闭
> 
> 在开启游戏前的等待房间，任何人都可以互相击杀，说明killhammer已开启。但在进入游戏后，猎人无法击杀。我并没有在代码层面和配置文件上做任何更改

需要在开始游戏之后尝试开启kill hammer
大厅中的kill hammer与游戏中的kill hammer并不是同一种，同时为了兼容ddnet模式，该mod中的锤子拥有三种状态

**Comment by cycode0527** [comment]
> > > 请检查DEVICE是否有无碰撞的buff，同时请检查投票中的kill hammer是否关闭
> > 
> > 
> > 在开启游戏前的等待房间，任何人都可以互相击杀，说明killhammer已开启。但在进入游戏后，猎人无法击杀。我并没有在代码层面和配置文件上做任何更改
> 
> 需要在开始游戏之后尝试开启kill hammer 大厅中的kill hammer与游戏中的kill hammer并不是同一种，同时为了兼容ddnet模式，该mod中的锤子拥有三种状态

我使用的是投票页面的killhammer.，无论是游戏内还是大厅内，都显示“先关闭才能打开”。

**Comment by LandmineHQ** [comment]
> > 
> > 
> > 需要在开始游戏之后尝试开启kill hammer 大厅中的kill hammer与游戏中的kill hammer并不是同一种，同时为了兼容ddnet模式，该mod中的锤子拥有三种状态
> 
> 我使用的是投票页面的killhammer.，无论是游戏内还是大厅内，都显示“先关闭才能打开”。

我已测试，默认配置下没有出现你所描述的问题，请你尝试拉取最新的dev版本进行编译

**Comment by cycode0527** [comment]
> > > 
> > > 
> > > 需要在开始游戏之后尝试开启kill hammer 大厅中的kill hammer与游戏中的kill hammer并不是同一种，同时为了兼容ddnet模式，该mod中的锤子拥有三种状态
> > 
> > 我使用的是投票页面的killhammer.，无论是游戏内还是大厅内，都显示“先关闭才能打开”。
> 
> 我已测试，默认配置下没有出现你所描述的问题，请你尝试拉取最新的dev版本进行编译
> 

收到，我将会进行重新编译再次实验

**Comment by cycode0527** [comment]
感谢作者，现在已经找到原因。在翻看character.cpp时，我认为有可能在判断进入U4时间段时的变量`isLoading`有关，因为isLoading的复制条件用到了+号，让我不解。果然这一bug已在commit：`beee5382b5225746fe61a3e8155cc6b4af749683`中修复。

另外我最后奇怪一件事：为毛我当时会下载到bug修复前的这个版本？
