### ISSUE TITLE
suggestion 单局结束后保留玩家皮肤

### ISSUE THREAD

**Issue by LandmineHQ** [landmineHQl/ddnet-hidden#10]
**Is your feature request related to a problem? Please describe.**
游戏结束后并不清楚哪个玩家在上局做了什么事情，所以最好是在一局结束后保留玩家的皮肤，下局开始后再进行刷新

**Comment by cycode0527** [comment]
自己给自己提suggestion的屑腐竹

**Comment by cycode0527** [comment]
由于大厅阶段是S0，所以这个皮肤很有可能一直保留到下一次开始，不会刷新为原本皮肤

**Comment by LandmineHQ** [comment]
> 由于大厅阶段是S0，所以这个皮肤很有可能一直保留到下一次开始，不会刷新为原本皮肤

就是要这个效果，新进的玩家显示自己的皮肤，游玩之后就一直显示上局的皮肤
