### ISSUE TITLE
[bug] 关于机器碰撞箱问题

### ISSUE THREAD

**Issue by cycode0527** [landmineHQl/ddnet-hidden#3]
原问题见#1
关于机器碰撞箱问题，已成功得到复现，如图：
![QQ截图20231219181705](https://github.com/landmineHQ/ddnet-hidden/assets/76815699/ad3e096b-10ff-43e8-979b-1894e14680c2)
![QQ截图20231219181922](https://github.com/landmineHQ/ddnet-hidden/assets/76815699/9a4cbb4d-9e6d-470a-9c3e-c756741e1d6a)
可注意到图一中的机器有不碰撞buff，而图二没有。这种差别在于，图一是**服务器创建后的第一局**，而后的局就是图二的情况。
显然，图二的情况是正常情况，而图一不是。当然对于一个常开的服务器来说，这个bug应该不算大。

**Comment by cycode0527** [comment]
刚查看了服务器刚开始的情况，所有的机器被放置在了“榴弹模式”右上角的一个小格子里，因此有了不碰撞buff。而这一状态直到游戏结束进入娃娃机才消失。因此我有理由认为，会不会**玩家和机器碰撞才是bug？**
在两局之间，机器始终处在娃娃机内。所以状态未刷新。

**Comment by cycode0527** [comment]
我现在已经发现，这并非代码问题，而是地图问题。由于我未找到打开机关4的代码，也就是释放假人的门，所以未能找到具体原因。但是，将门下面的碰撞buff复制给三号传送门可以解决这一问题。
![QQ截图20231219192123](https://github.com/landmineHQ/ddnet-hidden/assets/76815699/0048dff7-0dfd-49f1-89d1-4f783779dc3c)

**Comment by LandmineHQ** [comment]
此为地图BUG，需要联系地图作者FightFire进行解决，我已通知

**Comment by LandmineHQ** [comment]
地图作者已进行修复
