### ISSUE TITLE
[小小问题] 忍不住想问一下，那天那个给我猎人的原理是什么啊，代码里看到的是纯随机。。。

### ISSUE THREAD

**Issue by cycode0527** [landmineHQl/ddnet-hidden#6]
如题

**Comment by LandmineHQ** [comment]
没有，就是随机的，你说的已经涉及不良操作了，不可以这样做

**Comment by cycode0527** [comment]
> 没有，就是随机的，你说的已经涉及不良操作了，不可以这样做

还有这样的。。那么那天我当猎人纯粹巧合？？

**Comment by LandmineHQ** [comment]
> > 没有，就是随机的，你说的已经涉及不良操作了，不可以这样做
> 
> 还有这样的。。那么那天我当猎人纯粹巧合？？

是的

**Comment by cycode0527** [comment]
> 没有，就是随机的，你说的已经涉及不良操作了，不可以这样做

我倒不觉得是不良操作。作为管理员，甚至可以直接pause观察和缩小地图，早就不平衡了。。。至于担心的所谓抢猎人这回事，我觉得这事应该取决于管理员自己的想法和管理能力

**Comment by cycode0527** [comment]
那么作者大大可以先不管这个。我看看我能不能自己写一个出来，有时间试一下。。。。
